### ISSUE TITLE
Empty Episodes Lists

### ISSUE THREAD

**Issue by flashjmp** [darksky83/plugin.video.tviplayer#2]
Hi darksky83,

I hope you are still watching this issue list ;-)

We have been enjoying your fine Kodi addon for a while now and my wife is very actively using it to keep up with some telenovelas from her home country...

Unfortunately for the last two days any Episodes List come up empty. From what I could see in the kodi.log (I am somewhat familiar with coding, but have never written an kodi addon myself) the addon is successfully entering the addon.py portion and (with logging activated) it successfully passes the KODI-TVI-PLAYER Mode:16 portion of addon.py but I never see the listepisodes method invoked :-(

This is the relevant portion of the kodi.log:

20:23:30.696 T:1466954736   DEBUG: CWebServer[80]: request received for /jsonrpc
20:23:30.701 T:1958609840   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.tviplayer/?iconimage=http%3a%2f%2fwww.iol.pt%2fmultimedia%2foratvi%2fmultimedia%2fimagem%2fid%2f599416a80cf21d6c5360b49c&mode=16&name=Epis%c3%b3dios%20(85)&url=http%3a%2f%2ftviplayer.iol.pt%2fajax%2fmultimedias%2f593ad33d0cf277ced3014261%2f1%2fepisodios%2f1)
20:23:30.702 T:1958609840   DEBUG:   ParentPath = [plugin://plugin.video.tviplayer/?iconimage=http%3a%2f%2fwww.iol.pt%2fmultimedia%2foratvi%2fmultimedia%2fimagem%2fid%2f599416a80cf21d6c5360b49c&mode=13&name=A%20Herdeira&plot&url=http%3a%2f%2ftviplayer.iol.pt%2f%2fprograma%2fa-herdeira%2f593ad33d0cf277ced3014261]
20:23:30.737 T:1175540720   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.tviplayer] took 34 ms
20:23:30.739 T:1204810736   DEBUG: StartScript - calling plugin TVI Kodi Player('plugin://plugin.video.tviplayer/','65','?iconimage=http%3a%2f%2fwww.iol.pt%2fmultimedia%2foratvi%2fmultimedia%2fimagem%2fid%2f599416a80cf21d6c5360b49c&mode=16&name=Epis%c3%b3dios%20(85)&url=http%3a%2f%2ftviplayer.iol.pt%2fajax%2fmultimedias%2f593ad33d0cf277ced3014261%2f1%2fepisodios%2f1')
20:23:30.740 T:1390408688   DEBUG: Thread LanguageInvoker start, auto delete: false
20:23:30.740 T:1390408688    INFO: initializing python engine.
20:23:30.740 T:1390408688   DEBUG: CPythonInvoker(139, /home/osmc/.kodi/addons/plugin.video.tviplayer/addon.py): start processing
20:23:31.154 T:1390408688   DEBUG: -->Python Interpreter Initialized<--
20:23:31.154 T:1390408688   DEBUG: CPythonInvoker(139, /home/osmc/.kodi/addons/plugin.video.tviplayer/addon.py): the source file to load is "/home/osmc/.kodi/addons/plugin.video.tviplayer/addon.py"
20:23:31.155 T:1390408688   DEBUG: CPythonInvoker(139, /home/osmc/.kodi/addons/plugin.video.tviplayer/addon.py): setting the Python path to /home/osmc/.kodi/addons/plugin.video.tviplayer:/usr/lib/python2.7:/usr/lib/python2.7/plat-arm-linux-gnueabihf:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/usr/lib/python2.7/dist-packages/gtk-2.0
20:23:31.155 T:1390408688   DEBUG: CPythonInvoker(139, /home/osmc/.kodi/addons/plugin.video.tviplayer/addon.py): entering source directory /home/osmc/.kodi/addons/plugin.video.tviplayer
20:23:31.155 T:1390408688   DEBUG: CPythonInvoker(139, /home/osmc/.kodi/addons/plugin.video.tviplayer/addon.py): instantiating addon using automatically obtained id of "plugin.video.tviplayer" dependent on version 2.1.0 of the xbmc.python api
20:23:31.213 T:1958609840   DEBUG: ------ Window Init (DialogBusy.xml) ------
20:23:32.565 T:1390408688   DEBUG: TVI-KODI-PLAYER Mode: 16   URL: http://tviplayer.iol.pt/ajax/multimedias/593ad33d0cf277ced3014261/1/episodios/1  Name: Episódios (85)  IconImage: http://www.iol.pt/multimedia/oratvi/multimedia/imagem/id/599416a80cf21d6c5360b49c
20:23:32.668 T:1390408688   DEBUG: send:
20:23:32.668 T:1390408688   DEBUG: 'GET /ajax/multimedias/593ad33d0cf277ced3014261/1/episodios/1 HTTP/1.1\r\nAccept-Encoding: gzip\r\nConnection: close\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0\r\nHost: tviplayer.iol.pt\r\nReferer: http://tviplayer.iol.pt/\r\nCookie: JSESSIONID=2a086f960b850f7617b1e314445a\r\n\r\n'
20:23:32.918 T:1390408688   DEBUG: reply:
20:23:32.919 T:1390408688   DEBUG: 'HTTP/1.1 200 OK\r\n'
20:23:32.920 T:1390408688   DEBUG: header:
20:23:32.920 T:1390408688   DEBUG: Server: nginx/1.6.3
20:23:32.921 T:1390408688   DEBUG: header:
20:23:32.921 T:1390408688   DEBUG: Date: Thu, 04 Jan 2018 19:23:32 GMT
20:23:32.921 T:1390408688   DEBUG: header:
20:23:32.921 T:1390408688   DEBUG: Content-Type: text/html;charset=UTF-8
20:23:32.921 T:1390408688   DEBUG: header:
20:23:32.922 T:1390408688   DEBUG: Transfer-Encoding: chunked
20:23:32.922 T:1390408688   DEBUG: header:
20:23:32.922 T:1390408688   DEBUG: Connection: close
20:23:32.922 T:1390408688   DEBUG: header:
20:23:32.923 T:1390408688   DEBUG: Vary: Accept-Encoding
20:23:32.923 T:1390408688   DEBUG: header:
20:23:32.923 T:1390408688   DEBUG: X-Powered-By: Servlet/3.1 JSP/2.3 (Payara Server  4.1.1.154 #badassfish Java/Oracle Corporation/1.8)
20:23:32.923 T:1390408688   DEBUG: header:
20:23:32.923 T:1390408688   DEBUG: Set-Cookie: JSESSIONID=2a0e5efb5819d178115c1aab1144; Path=/; HttpOnly
20:23:32.923 T:1390408688   DEBUG: header:
20:23:32.924 T:1390408688   DEBUG: Access-Control-Allow-Origin: *
20:23:32.924 T:1390408688   DEBUG: header:
20:23:32.924 T:1390408688   DEBUG: Content-Encoding: gzip
20:23:32.961 T:1390408688    INFO: CPythonInvoker(139, /home/osmc/.kodi/addons/plugin.video.tviplayer/addon.py): script successfully run
20:23:32.985 T:1108431856   DEBUG: Thread BackgroundLoader start, auto delete: false
20:23:33.009 T:1108431856   DEBUG: Thread BackgroundLoader 1108431856 terminating
20:23:33.038 T:1175540720 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
20:23:33.039 T:1175540720   DEBUG: COMXImageFile::ReadFile special://skin/backgrounds/default_bg.jpg GetCodingType=0x7fffffff (1920x1080)
20:23:33.039 T:1175540720  NOTICE: LoadJpeg: unable to load special://skin/backgrounds/default_bg.jpg
20:23:33.098 T:1958609840   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
20:23:33.345 T:1390408688    INFO: Python script stopped
20:23:33.345 T:1390408688   DEBUG: Thread LanguageInvoker 1390408688 terminating
20:23:33.955 T:1175540720   DEBUG: DoWork - took 918 ms to load special://skin/backgrounds/default_bg.jpg

Thanks for looking into this!

Cheers,
Tomas from Hamburg

**Comment by darksky83** [comment]
Will be fix in next version 0.3.0
